import { DeployableType, ProjectileType, VisualEffect } from '@/types/enums';
import { WeaponCategory, WeaponConfig, WeaponType } from './type';

export const WEAPON_TYPES: Record<WeaponType | 'minibanana', WeaponConfig> = {
  [WeaponType.PISTOL]: {
    name: 'Pistolet',
    emoji: '🔫',
    cooldown: 500,
    damage: 10,
    bulletSpeed: 900,
    bulletCount: 1,
    spread: 0,
    color: '#ffff00',
    range: 265,
    weaponCategory: WeaponCategory.GUN,
    projectileMass: 0.6,
    projectileType: ProjectileType.STANDARD,
  },
  [WeaponType.SMG]: {
    name: 'SMG',
    emoji: '💨',
    cooldown: 150,
    damage: 5,
    bulletSpeed: 900,
    bulletCount: 1,
    spread: 15,
    color: '#ffa500',
    range: 215,
    weaponCategory: WeaponCategory.GUN,
    projectileMass: 0.4,
    projectileType: ProjectileType.STANDARD,
  },
  [WeaponType.SHOTGUN]: {
    name: 'Shotgun',
    emoji: '💥',
    cooldown: 800,
    damage: 8,
    bulletSpeed: 420,
    bulletCount: 5,
    spread: 30,
    color: '#ff4444',
    range: 140,
    weaponCategory: WeaponCategory.GUN,
    projectileMass: 0.4,
    projectileType: ProjectileType.STANDARD,
  },
  [WeaponType.SNIPER]: {
    name: 'Snajperka',
    emoji: '🎯',
    cooldown: 1500,
    damage: 50,
    bulletSpeed: 900,
    bulletCount: 1,
    spread: 0,
    pierceCount: 2,
    color: '#00ffff',
    range: 400,
    weaponCategory: WeaponCategory.GUN,
    projectileMass: 1.0,
    projectileType: ProjectileType.STANDARD,
  },
  [WeaponType.LASER]: {
    name: 'Laser',
    emoji: '⚡',
    cooldown: 80,
    damage: 4,
    bulletSpeed: 1200,
    bulletCount: 1,
    spread: 5,
    color: '#ff00ff',
    range: 350,
    weaponCategory: WeaponCategory.GUN,
    projectileMass: 0.1,
    projectileType: ProjectileType.STANDARD,
  },
  [WeaponType.MINIGUN]: {
    name: 'Minigun',
    emoji: '🔥',
    cooldown: 30,
    damage: 3,
    bulletSpeed: 720,
    bulletCount: 1,
    spread: 20,
    color: '#ff6600',
    range: 160,
    weaponCategory: WeaponCategory.GUN,
    projectileMass: 0.12,
    projectileType: ProjectileType.STANDARD,
  },
  [WeaponType.BAZOOKA]: {
    name: 'Bazooka',
    emoji: '🚀',
    cooldown: 2000,
    damage: 80,
    bulletSpeed: 300,
    bulletCount: 1,
    spread: 0,
    explosive: true,
    explosionRadius: 80,
    explosionEffect: VisualEffect.STANDARD,
    color: '#ff0000',
    bulletRadius: 10,
    range: 310,
    weaponCategory: WeaponCategory.ROCKET,
    projectileMass: 2.0,
    projectileType: ProjectileType.ROCKET,
  },
  [WeaponType.FLAMETHROWER]: {
    name: 'Miotacz Ognia',
    emoji: '🔥',
    cooldown: 82,
    damage: 2,
    bulletSpeed: 360,
    bulletCount: 3,
    spread: 40,
    color: '#ff4400',
    bulletRadius: 6,
    shortRange: true,
    maxDistance: 120,
    range: 120,
    weaponCategory: WeaponCategory.SPECIAL,
    projectileMass: 0.01,
    projectileType: ProjectileType.FLAMETHROWER,
  },
  [WeaponType.MINES]: {
    name: 'Miny',
    emoji: '💣',
    cooldown: 3000,
    damage: 65,
    bulletSpeed: 0,
    bulletCount: 1,
    spread: 0,
    explosive: true,
    explosionRadius: 70,
    explosionEffect: VisualEffect.STANDARD,
    color: '#333333',
    bulletRadius: 12,
    range: 9999,
    weaponCategory: WeaponCategory.DEPLOYABLE,
    projectileMass: 1.0,
    deployableType: DeployableType.MINE,
  },
  [WeaponType.NUKE]: {
    name: 'Wyrzutnia Nuklearna',
    emoji: '☢️',
    cooldown: 8000,
    damage: 300,
    bulletSpeed: 180,
    bulletCount: 1,
    spread: 0,
    explosive: true,
    explosionRadius: 200,
    explosionEffect: VisualEffect.NUKE,
    color: '#00ff00',
    bulletRadius: 15,
    range: 9999,
    weaponCategory: WeaponCategory.ROCKET,
    projectileMass: 5.0,
    projectileType: ProjectileType.NUKE,
  },
  [WeaponType.SCYTHE]: {
    name: 'Kosa Kubusia',
    emoji: '🌙',
    cooldown: 1225,
    damage: 38,
    bulletSpeed: 360,
    bulletCount: 1,
    spread: 0,
    pierceCount: 3,
    color: '#9932cc',
    bulletRadius: 20,
    range: 230,
    weaponCategory: WeaponCategory.MELEE,
    projectileMass: 2.5,
    projectileType: ProjectileType.SCYTHE,
    // TODO projectile section?
    rotationSpeed: 4, // ~0.6 rotations per second
  },
  [WeaponType.SWORD]: {
    name: 'Miecz Kamilka',
    emoji: '⚔️',
    cooldown: 800,
    damage: 14,
    bulletSpeed: 720,
    bulletCount: 3,
    spread: 60,
    color: '#c0c0c0',
    bulletRadius: 8,
    shortRange: true,
    maxDistance: 100,
    range: 100,
    weaponCategory: WeaponCategory.MELEE,
    projectileMass: 0.4,
    projectileType: ProjectileType.SWORD,
  },
  [WeaponType.HOLY_GRENADE]: {
    name: 'Święty Granat',
    emoji: '✝️',
    cooldown: 3000,
    damage: 100,
    bulletSpeed: 360,
    bulletCount: 1,
    spread: 0,
    explosive: true,
    explosionRadius: 120,
    explosionEffect: VisualEffect.HOLY,
    color: '#ffd700',
    bulletRadius: 12,
    range: 275,
    weaponCategory: WeaponCategory.GRENADE,
    projectileMass: 1,
    explosiveRange: 275,
    projectileType: ProjectileType.HOLY_GRENADE,
    friction: 0.02,
  },
  [WeaponType.BANANA]: {
    name: 'Banan z Worms',
    emoji: '🍌',
    cooldown: 2300,
    damage: 45,
    bulletSpeed: 420,
    bulletCount: 1,
    spread: 0,
    explosive: true,
    explosionRadius: 90,
    explosionEffect: VisualEffect.BANANA,
    color: '#ffff00',
    bulletRadius: 10,
    range: 235,
    weaponCategory: WeaponCategory.GRENADE,
    projectileMass: 0.7,
    explosiveRange: 235,
    projectileType: ProjectileType.BANANA,
    rotationSpeed: 4, // ~0.6 rotations per second
    friction: 0.028,
  },
  [WeaponType.CROSSBOW]: {
    name: 'Kusza Przebijająca',
    emoji: '🏹',
    cooldown: 900,
    damage: 52,
    bulletSpeed: 840,
    bulletCount: 1,
    spread: 0,
    pierceCount: 3,
    color: '#8b4513',
    bulletRadius: 6,
    range: 320,
    weaponCategory: WeaponCategory.GUN,
    projectileMass: 1.0,
    projectileType: ProjectileType.CROSSBOW_BOLT,
  },

  // Internal type - mini banana spawned by main banana
  minibanana: {
    name: 'Mini Banan',
    emoji: '🍌',
    cooldown: 0,
    damage: 16,
    bulletSpeed: 600,
    bulletCount: 1,
    spread: 0,
    explosive: true,
    explosionRadius: 45,
    explosionEffect: VisualEffect.BANANA,
    color: '#ffff00',
    bulletRadius: 6,
    range: 80,
    weaponCategory: WeaponCategory.GRENADE,
    projectileMass: 0.6,
    explosiveRange: 80,
    projectileType: ProjectileType.MINI_BANANA,
    rotationSpeed: 6, // ~0.8 rotations per second
    friction: 0.09,
  },
} as const;
